### ISSUE TITLE
Fetch branches as well

### ISSUE THREAD

**Issue by Mihailoff** [FitchLearning/satisfy#2]
I find this library very handy and it can be improved by adding branches too. It is bad practice to depend on branch because it simple unstable. But unfortunately there might be repos without any tags and only "tagging" on particular commit hash can help.

**Comment by limetec** [comment]
We also have this "problem". Our private library depends on a library which does not have any tags (only master branch) nor a composer.json. Of course we know that this is risky but at the moment we cannot change this.

In our satis.json we added the github repository:
```
    {
      "type": "package",
      "package": {
        "name": "jquery-archive/jquery-metadata",
        "version": "master",
        "source": {
          "url": "https://github.com/jquery-archive/jquery-metadata",
          "type": "git",
          "reference": "master"
        }
      }
    }
```
When building the satis.json with satisfy and after that build satis the library gets shown on the satis browser page with version "master".

In our libraries composer.json we have 
```
"require": {
    "jquery-archive/jquery-metadata": "master"
}
```

But when updating composer it errors that version *@dev cannot be found. When we put the repository in the composer.json itself, it works.

But as written above we want to use this private library on another project and composer cannot load repositories recursively. That is why I would like a add this tag-less repository to Satis so the new project can require our private library.
